/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TouristRoutes;

import Collections.Exception.ElementNotFoundException;
import Collections.NonLinear.Network.DiNetworkAdjMatrixTrajeto;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author luis_
 * @param <T>
 */
public class TouristRouteInterface extends javax.swing.JFrame {

    private DiNetworkAdjMatrixTrajeto<String> touristRoute;

    /**
     * Creates new form TouristRouteInterface
     *
     * @param touristRoute
     */
    public TouristRouteInterface(DiNetworkAdjMatrixTrajeto<String> touristRoute) {
        initComponents();
        this.touristRoute = touristRoute;
    }
    
    public TouristRouteInterface(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        CidadeOrigem = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        CidadeDestino = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        DuracaoMaximo = new javax.swing.JCheckBox();
        DuracaoTotalMaxima = new javax.swing.JTextField();
        EsperaMaximaParagem = new javax.swing.JCheckBox();
        TempoEsperaMaximoParagem = new javax.swing.JTextField();
        EsperaTotal = new javax.swing.JCheckBox();
        TempoEsperaTotal = new javax.swing.JTextField();
        PrecoTotal = new javax.swing.JCheckBox();
        PrecoTotalMaximo = new javax.swing.JTextField();
        PrecoMaximoTroco = new javax.swing.JCheckBox();
        PrecoMaximoTrajeto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tourist-Routes");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jSplitPane1.setDividerLocation(500);
        jSplitPane1.setToolTipText("");
        jSplitPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSplitPane1.setEnabled(false);
        jSplitPane1.setMaximumSize(new java.awt.Dimension(1096, 500));
        jSplitPane1.setMinimumSize(new java.awt.Dimension(1096, 500));

        CidadeOrigem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Cidade Origem");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Cidade Destino");

        CidadeDestino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Critérios de pesquisa");

        DuracaoMaximo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DuracaoMaximo.setText("Duração total maxima");
        DuracaoMaximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DuracaoMaximoActionPerformed(evt);
            }
        });

        DuracaoTotalMaxima.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DuracaoTotalMaxima.setMinimumSize(new java.awt.Dimension(438, 23));
        DuracaoTotalMaxima.setPreferredSize(new java.awt.Dimension(438, 23));

        EsperaMaximaParagem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EsperaMaximaParagem.setText("Tempo de espera máximo em cada paragem ");
        EsperaMaximaParagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EsperaMaximaParagemActionPerformed(evt);
            }
        });

        TempoEsperaMaximoParagem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TempoEsperaMaximoParagem.setVisible(false);

        EsperaTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EsperaTotal.setText("Tempo de espera total");
        EsperaTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EsperaTotalActionPerformed(evt);
            }
        });

        TempoEsperaTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TempoEsperaTotal.setVisible(false);

        PrecoTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PrecoTotal.setText("Preço total máximo ");
        PrecoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecoTotalActionPerformed(evt);
            }
        });

        PrecoTotalMaximo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PrecoTotalMaximo.setVisible(false);

        PrecoMaximoTroco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PrecoMaximoTroco.setText("Preço máximo por troço");
        PrecoMaximoTroco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecoMaximoTrocoActionPerformed(evt);
            }
        });

        PrecoMaximoTrajeto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PrecoMaximoTrajeto.setVisible(false);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton1.setText("Submeter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        DuracaoTotalMaxima.setVisible(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PrecoMaximoTroco)
                    .addComponent(PrecoTotal)
                    .addComponent(EsperaTotal)
                    .addComponent(EsperaMaximaParagem)
                    .addComponent(DuracaoMaximo)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(CidadeDestino)
                            .addContainerGap())
                        .addComponent(jLabel1)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(344, 344, 344))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(CidadeOrigem)
                            .addContainerGap()))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(PrecoMaximoTrajeto, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PrecoTotalMaximo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TempoEsperaTotal, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TempoEsperaMaximoParagem, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(DuracaoTotalMaxima, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jButton1)
                .addGap(101, 101, 101)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CidadeOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CidadeDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DuracaoMaximo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DuracaoTotalMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EsperaMaximaParagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TempoEsperaMaximoParagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EsperaTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TempoEsperaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PrecoTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PrecoTotalMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PrecoMaximoTroco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PrecoMaximoTrajeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 666, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened


    }//GEN-LAST:event_formWindowOpened

    private void verificarCidade(String str) throws ElementNotFoundException {
        int i = 0;
        while (i < touristRoute.getNumVertices() && !str.equals(touristRoute.getVertices()[i])) {
            i++;
        }
        if (i == touristRoute.getNumVertices()) {
            throw new ElementNotFoundException("Elemento nao existe");
        }
    }

    private double[] verificarCriterio(JCheckBox[] checkBox, JTextField[] textField) {
        int i = 0;
        double[] valorCriterio = new double[textField.length];
        while (i < checkBox.length) {
            if (checkBox[i].isSelected()) {
                valorCriterio[i] = Double.parseDouble(textField[i].getText());
            } else {
                valorCriterio[i] = Double.NEGATIVE_INFINITY;
            }
            i++;
        }

        return valorCriterio;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JCheckBox[] checkBox = {DuracaoMaximo, EsperaMaximaParagem, EsperaTotal, PrecoMaximoTroco, PrecoTotal};
        JTextField[] textField = {DuracaoTotalMaxima, TempoEsperaMaximoParagem, TempoEsperaTotal, PrecoMaximoTrajeto, PrecoTotalMaximo};
        double[] valoresCriterios = new double[checkBox.length];
        String str = "";
        try {
            verificarCidade(CidadeOrigem.getText());
        } catch (Exception ex) {
            str += "Cidade Origem Inexistente\n";
        }
        try {
            verificarCidade(CidadeDestino.getText());
        } catch (Exception ex) {
            str += "Cidade Destino Inexistente\n";
        }
        try {
            valoresCriterios = verificarCriterio(checkBox, textField);
        } catch (Exception e) {
            str += "Valor de critérios invalidos\n";
        }
        if (str != "") {
            JOptionPane.showMessageDialog(jPanel1, str, "Value Invalid", JOptionPane.ERROR_MESSAGE);

        } else {
            //funçao shortpath
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DuracaoMaximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DuracaoMaximoActionPerformed

        if (DuracaoMaximo.isSelected()) {
            DuracaoTotalMaxima.setVisible(true);
        } else {
            DuracaoTotalMaxima.setVisible(false);
        }
    }//GEN-LAST:event_DuracaoMaximoActionPerformed

    private void EsperaMaximaParagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EsperaMaximaParagemActionPerformed
        if (EsperaMaximaParagem.isSelected()) {
            TempoEsperaMaximoParagem.setVisible(true);
        } else {
            TempoEsperaMaximoParagem.setVisible(false);
        }
    }//GEN-LAST:event_EsperaMaximaParagemActionPerformed

    private void EsperaTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EsperaTotalActionPerformed
        if (EsperaTotal.isSelected()) {
            TempoEsperaTotal.setVisible(true);
        } else {
            TempoEsperaTotal.setVisible(false);
        }
    }//GEN-LAST:event_EsperaTotalActionPerformed

    private void PrecoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecoTotalActionPerformed
        if (PrecoTotal.isSelected()) {
            PrecoTotalMaximo.setVisible(true);
        } else {
            PrecoTotalMaximo.setVisible(false);
        }
    }//GEN-LAST:event_PrecoTotalActionPerformed

    private void PrecoMaximoTrocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecoMaximoTrocoActionPerformed
        if (PrecoMaximoTroco.isSelected()) {
            PrecoMaximoTrajeto.setVisible(true);
        } else {
            PrecoMaximoTrajeto.setVisible(false);
        }
    }//GEN-LAST:event_PrecoMaximoTrocoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Menu(this.touristRoute).setVisible(true);
        this.dispose();  
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TouristRouteInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TouristRouteInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TouristRouteInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TouristRouteInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                
                new TouristRouteInterface().setVisible(true);
                //mapa.startMapa(touristRoutes.getVertices(), touristRoutes.getNumVertices());
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CidadeDestino;
    private javax.swing.JTextField CidadeOrigem;
    private javax.swing.JCheckBox DuracaoMaximo;
    private javax.swing.JTextField DuracaoTotalMaxima;
    private javax.swing.JCheckBox EsperaMaximaParagem;
    private javax.swing.JCheckBox EsperaTotal;
    private javax.swing.JTextField PrecoMaximoTrajeto;
    private javax.swing.JCheckBox PrecoMaximoTroco;
    private javax.swing.JCheckBox PrecoTotal;
    private javax.swing.JTextField PrecoTotalMaximo;
    private javax.swing.JTextField TempoEsperaMaximoParagem;
    private javax.swing.JTextField TempoEsperaTotal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
